using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EasyAppDev.Blazor.Store.Generators;

/// <summary>
/// Source generator that creates setter and updater methods for store state records.
/// </summary>
[Generator]
public class StoreGenerator : IIncrementalGenerator
{
    private const string StoreAttributeName = "EasyAppDev.Blazor.Store.Generators.StoreAttribute";
    private const string ImmutableCollectionAttributeName = "EasyAppDev.Blazor.Store.Generators.ImmutableCollectionAttribute";
    private const string ComputedAttributeName = "EasyAppDev.Blazor.Store.Generators.ComputedAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all records with [Store] attribute
        var recordDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                StoreAttributeName,
                predicate: static (node, _) => node is RecordDeclarationSyntax,
                transform: static (ctx, _) => GetRecordInfo(ctx))
            .Where(static r => r is not null);

        // Generate source for each record
        context.RegisterSourceOutput(recordDeclarations, static (ctx, record) =>
        {
            if (record is null) return;
            var source = GenerateSource(record);
            ctx.AddSource($"{record.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static RecordInfo? GetRecordInfo(GeneratorAttributeSyntaxContext context)
    {
        var recordSymbol = context.TargetSymbol as INamedTypeSymbol;
        if (recordSymbol is null) return null;

        var recordSyntax = context.TargetNode as RecordDeclarationSyntax;
        if (recordSyntax is null) return null;

        // Get attribute data
        var storeAttribute = context.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == StoreAttributeName);

        var generateActions = storeAttribute?.NamedArguments
            .FirstOrDefault(kvp => kvp.Key == "GenerateActions")
            .Value.Value as bool? ?? false;

        var generateWithMethods = storeAttribute?.NamedArguments
            .FirstOrDefault(kvp => kvp.Key == "GenerateWithMethods")
            .Value.Value as bool? ?? false;

        // Get namespace
        var ns = recordSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : recordSymbol.ContainingNamespace.ToDisplayString();

        // Get properties from primary constructor parameters
        var properties = new List<PropertyInfo>();

        foreach (var member in recordSymbol.GetMembers())
        {
            if (member is not IPropertySymbol property) continue;
            if (property.IsStatic || property.IsIndexer) continue;
            if (!property.CanBeReferencedByName) continue;

            // Skip synthesized record properties
            if (property.Name == "EqualityContract") continue;
            if (property.IsImplicitlyDeclared) continue;

            // Check for Computed attribute
            var hasComputed = property.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == ComputedAttributeName);
            if (hasComputed) continue;

            // Check for ImmutableCollection attribute
            var hasImmutableCollection = property.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == ImmutableCollectionAttributeName);

            // Get generic type for collections
            string? elementType = null;
            if (hasImmutableCollection && property.Type is INamedTypeSymbol namedType)
            {
                if (namedType.TypeArguments.Length > 0)
                {
                    elementType = namedType.TypeArguments[0].ToDisplayString();
                }
            }

            properties.Add(new PropertyInfo(
                property.Name,
                property.Type.ToDisplayString(),
                property.NullableAnnotation == NullableAnnotation.Annotated,
                hasImmutableCollection,
                elementType));
        }

        return new RecordInfo(
            recordSymbol.Name,
            ns,
            properties,
            generateActions,
            generateWithMethods);
    }

    private static string GenerateSource(RecordInfo record)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (record.Namespace is not null)
        {
            sb.AppendLine($"namespace {record.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial record {record.Name}");
        sb.AppendLine("{");

        foreach (var prop in record.Properties)
        {
            GeneratePropertyMethods(sb, record.Name, prop, record.GenerateWithMethods);
        }

        sb.AppendLine("}");

        // Generate actions if requested
        if (record.GenerateActions)
        {
            sb.AppendLine();
            GenerateActions(sb, record);
        }

        return sb.ToString();
    }

    private static void GeneratePropertyMethods(
        StringBuilder sb,
        string recordName,
        PropertyInfo prop,
        bool generateWith)
    {
        var propName = prop.Name;
        var propType = prop.Type;

        // Set method
        sb.AppendLine($"    /// <summary>Sets the {propName} property.</summary>");
        sb.AppendLine($"    public {recordName} Set{propName}({propType} value)");
        sb.AppendLine($"        => this with {{ {propName} = value }};");
        sb.AppendLine();

        // With method (alias for Set)
        if (generateWith)
        {
            sb.AppendLine($"    /// <summary>Sets the {propName} property (alias for Set{propName}).</summary>");
            sb.AppendLine($"    public {recordName} With{propName}({propType} value)");
            sb.AppendLine($"        => this with {{ {propName} = value }};");
            sb.AppendLine();
        }

        // Update method
        sb.AppendLine($"    /// <summary>Updates the {propName} property using a transform function.</summary>");
        sb.AppendLine($"    public {recordName} Update{propName}(System.Func<{propType}, {propType}> updater)");
        sb.AppendLine($"        => this with {{ {propName} = updater({propName}) }};");
        sb.AppendLine();

        // Collection methods
        if (prop.IsImmutableCollection && prop.ElementType is not null)
        {
            var elemType = prop.ElementType;

            // Add method
            sb.AppendLine($"    /// <summary>Adds an item to {propName}.</summary>");
            sb.AppendLine($"    public {recordName} Add{GetSingular(propName)}({elemType} item)");
            sb.AppendLine($"        => this with {{ {propName} = {propName}.Add(item) }};");
            sb.AppendLine();

            // Remove method
            sb.AppendLine($"    /// <summary>Removes an item from {propName}.</summary>");
            sb.AppendLine($"    public {recordName} Remove{GetSingular(propName)}({elemType} item)");
            sb.AppendLine($"        => this with {{ {propName} = {propName}.Remove(item) }};");
            sb.AppendLine();

            // Clear method
            sb.AppendLine($"    /// <summary>Clears all items from {propName}.</summary>");
            sb.AppendLine($"    public {recordName} Clear{propName}()");
            sb.AppendLine($"        => this with {{ {propName} = {propName}.Clear() }};");
            sb.AppendLine();
        }
    }

    private static void GenerateActions(StringBuilder sb, RecordInfo record)
    {
        sb.AppendLine($"/// <summary>Generated actions for {record.Name}.</summary>");
        sb.AppendLine($"public static partial class {record.Name}Actions");
        sb.AppendLine("{");

        foreach (var prop in record.Properties)
        {
            sb.AppendLine($"    /// <summary>Action to set {prop.Name}.</summary>");
            sb.AppendLine($"    public record Set{prop.Name}({prop.Type} Value) : EasyAppDev.Blazor.Store.Actions.IAction;");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        // Generate reducer extension
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Generated reducer extension for {record.Name}.</summary>");
        sb.AppendLine($"public static partial class {record.Name}ReducerExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Registers all generated reducers for {record.Name} actions.</summary>");
        sb.AppendLine($"    public static EasyAppDev.Blazor.Store.Actions.ActionDispatcher<{record.Name}> WithGeneratedReducers(");
        sb.AppendLine($"        this EasyAppDev.Blazor.Store.Actions.ActionDispatcher<{record.Name}> dispatcher)");
        sb.AppendLine("    {");
        sb.AppendLine("        return dispatcher");

        foreach (var prop in record.Properties)
        {
            sb.AppendLine($"            .Register<{record.Name}Actions.Set{prop.Name}>((s, a) => s.Set{prop.Name}(a.Value))");
        }

        // Remove the last newline and add semicolon
        sb.Length -= "\r\n".Length; // Assume Windows line endings; cross-platform handled by StringBuilder
        if (sb[sb.Length - 1] == '\n') sb.Length--; // Handle Unix line endings
        if (sb.Length > 0 && sb[sb.Length - 1] == '\r') sb.Length--;
        sb.AppendLine(";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string GetSingular(string plural)
    {
        // Simple singularization - remove trailing 's' or 'es'
        if (plural.EndsWith("ies", StringComparison.Ordinal))
            return plural.Substring(0, plural.Length - 3) + "y";
        if (plural.EndsWith("es", StringComparison.Ordinal))
            return plural.Substring(0, plural.Length - 2);
        if (plural.EndsWith("s", StringComparison.Ordinal))
            return plural.Substring(0, plural.Length - 1);
        return plural;
    }

    private sealed class RecordInfo
    {
        public string Name { get; }
        public string? Namespace { get; }
        public List<PropertyInfo> Properties { get; }
        public bool GenerateActions { get; }
        public bool GenerateWithMethods { get; }

        public RecordInfo(
            string name,
            string? ns,
            List<PropertyInfo> properties,
            bool generateActions,
            bool generateWithMethods)
        {
            Name = name;
            Namespace = ns;
            Properties = properties;
            GenerateActions = generateActions;
            GenerateWithMethods = generateWithMethods;
        }
    }

    private sealed class PropertyInfo
    {
        public string Name { get; }
        public string Type { get; }
        public bool IsNullable { get; }
        public bool IsImmutableCollection { get; }
        public string? ElementType { get; }

        public PropertyInfo(
            string name,
            string type,
            bool isNullable,
            bool isImmutableCollection,
            string? elementType)
        {
            Name = name;
            Type = type;
            IsNullable = isNullable;
            IsImmutableCollection = isImmutableCollection;
            ElementType = elementType;
        }
    }
}
